- name: Print start message
  debug:
    msg: Started building Chat Worker

- name: Create output directory
  file:
    path: docker-output
    state: directory

- name: Clean and build gradle project
  shell: cd ../ && ./gradlew clean distTar

- name: Gather git information
  import_tasks: git-info.yml

- name: Generate the Dockerfile
  template:
    src: docker/Dockerfile-prod.j2
    dest: docker-output/Dockerfile
  vars:
    build_timestamp: "{{ ansible_date_time.iso8601 }}"

- name: Build Docker image
  shell: |
    docker build \
      -f docker-output/Dockerfile \
      -t chat-worker:latest \
      -t chat-worker:{{ git_branch }}-{{ git_commit }} \
      -t chat-worker:{{ git_branch }}-{{ ansible_date_time.iso8601_basic_short }} \
      ../

- name: Clean up output directory
  file:
    path: docker-output
    state: absent

- name: Print finish message
  debug:
    msg: Completed building Chat Worker